title: Hyogi Sim
description: Hyogi Sim's personal website
sitename: Hyogi Sim
url: https://sandrain.github.io
sass:
  sass_dir: /assets/_sass
  style: :compressed
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME

scholar:
  locale: en
  sort_by: year
  order: descending,descending
  source: _bibliography
  bibliography: publications
#  group_by: year
#  group_order: descending
